from .common import (
    Singleton,
    extract_code_block_contents,
    extract_python_block,
    extract_yaml_block,
    get_hf_access_token,
    parse_markup_tag,
    prepend_repo_root,
    read_json,
    read_json_lines,
    read_yaml,
    write_json,
    write_json_lines,
    write_yaml,
)
from .llm_job import run_llm_job
from .puzzle_utils import (
    extract_barc_concepts,
    extract_barc_seed_comment_sections,
    get_arc_problem_by_id,
    get_puzzle_url,
    load_arc_data,
    load_barc_seeds,  # legacy function (keeping to recall seed puzzle order)
    remove_barc_concepts_from_solution,
)
from .visualization import (
    display_img_file,
    draw_io_grids,
    example_repr,
    grid_repr,
    task_repr,
    visualize_barc_problem,
    visualize_problem,
)

__all__ = [
    "parse_markup_tag",
    "prepend_repo_root",
    "read_json",
    "write_json",
    "read_json_lines",
    "write_json_lines",
    "read_yaml",
    "write_yaml",
    "extract_code_block_contents",
    "extract_yaml_block",
    "extract_python_block",
    "Singleton",
    "get_hf_access_token",
    "extract_barc_concepts",
    "extract_barc_seed_comment_sections",
    "get_puzzle_url",
    "load_arc_data",
    "load_barc_seeds",  # legacy function
    "remove_barc_concepts_from_solution",
    "get_arc_problem_by_id",
    "display_img_file",
    "draw_io_grids",
    "display_img_file",
    "grid_repr",
    "example_repr",
    "task_repr",
    "visualize_barc_problem",
    "visualize_problem",
    "run_llm_job",
]
