defaults:
  - /model: gpt41
  - /generation: gen_default

problems: data/testbeds/validation_n100_uids.json
# description_file: data/vlm_desc_retrieval/two_step/validation_n100_desc.json
description_file: data/descriptions/gpt41_vlm.json
# description_file: data/descriptions/o4m_vlm.json
lesson_file: data/lessons/from_trace_fs/parsed_lessons.json

top_k: 5
situation_only: false
use_hint_v2: false

# choices: null (single), "concatenate", "llm_summary"
ensemble_method: null

summary_generation:
  temperature: 0.0
  max_tokens: 1024


mem_str_path: null
mem_path: null
