defaults:
- /model: gpt41
- /generation: gen_default

# instruction_block_file: data/abstract_anno/annotation_instruction_v7.yaml
instruction_block_file: data/abstract_anno/op1/op1_yaml_fmt.yaml
# hand_annotations_file: data/abstract_anno/icl_anno_v8.yaml
hand_annotations_file: data/abstract_anno/op1/opus1.yaml

# null for barc_seeds
problem_ids: null
solutions: null
# limit_problems: null
limit_problems: 10 


# for phase 2: concept gen
# pseudocode: outputs/2025-07-08/22-08-41/phase1.json
pseudocode: outputs/2025-07-09/16-46-48/initial_analysis.json
# batching for mem updates
batch_size: 10

# anno_fmt_block_path = DATA_DIR / "abstract_anno/op1/op1_yaml_fmt.yaml"
# anno_instr_template_path = DATA_DIR / "abstract_anno/op1/op1_instructions.txt"
# anno_fmt_block = anno_fmt_block_path.read_text().strip()
# anno_instr_template = anno_instr_template_path.read_text().strip()
# hand_anno_path = DATA_DIR / "abstract_anno/op1/opus1.yaml"
# hand_anno = read_yaml(hand_anno_path)
