defaults:
  - _self_
  - /model: gpt41
  - /data: val100
  - /generation: gen_default

data:
  num_problems: 100

mode: image_caption # options: image_caption; TODO: text, text_object
skip_concept_list: false # whether to remove concept list from description prompt entirey
concept_list: null # null for STATIC CONCEPT LIST from hypothesis search
include_puzzle_text: false
